In [1]:
import pandas as pd 
import numpy as np

In [2]:
# Inisialisasi Data
df = pd.read_csv('data_raw/homework.csv', sep=',')
df.columns = df.columns.str.strip()

In [3]:
# Mengubah Format
# Mengubah Format Subject dan Assignment_Name (memastikan format dengan benar)
df['Subject'] = df['Subject'].str.title()
df['Assignment_Name'] = df['Assignment_Name'].str.title()

# Mengubah Format Due_Date
df['Due_Date'] = pd.to_datetime(df['Due_Date'], format='mixed', dayfirst=True)

df.head(15)

,Student_ID,Subject,Assignment_Name,Due_Date,Status,Grade_Feedback,Guardian_Signature
0,S12002,Science,Record.,2024-09-10,❌,C-,Yes
1,S01255,History,Head Baby.,2024-10-16,❌,A+,No
2,S04968,Arabic,Keep Audience Medical Free.,2025-02-11,Done,A+,Yes
3,S07925,Geography,Three Half Peace.,2024-10-03,Done,A+,
4,S09980,Geography,Assume Particularly.,2024-12-01,✅,B-,No
5,S08309,Geography,Four From Kind Dark.,2024-12-19,Done,A,No
6,S11121,Math,Analysis Late Human.,2024-11-10,❌,F,Yes
7,S00175,Arabic,Shake By.,2024-09-09,Done,A,No
8,S02439,Geography,Oil Education Large Wonder.,2025-01-01,✅,C,No
9,S08144,Math,Never Bar Time Personal.,2024-10-15,❌,A+,No
10,S08545,Math,Deal Music.,2025-07-02,✔,F,No
11,S00424,History,Sister However.,2024-09-28,✅,B,
12,S00568,Math,Range Huge.,2025-01-28,✔,A,Yes
13,S07048,Arabic,Music Build Check Force.,2025-02-01,✅,A+,
14,S08771,Science,Strategy.,2025-02-26,❌,A+,Yes

In [4]:
# Feature Engineering
# Mengubah Data yang Tidak Sesuai pada Kolom Status
df['Status'] = df['Status'].str.title()

# Mencegah error jika ada baris yang kosong (None/NaN) dengan contains -> na=False
condition_status = [
    df['Status'].str.contains('✅|✔', na=False),
    df['Status'].str.contains('❌', na=False)
]

choice_status = ['Done', 'Not Done']

# Menerapkan perubahan, defaultnya mempertahankan nilai asli jika tidak ada simbol
df['Status'] = np.select(condition_status, choice_status, default=df['Status'])

# Mengubah Nilai yang Kosong (None/NaN) menjadi - 
df['Guardian_Signature'] = df['Guardian_Signature'].str.strip()
df['Guardian_Signature'] = df['Guardian_Signature'].replace('', '-')

df.head(15)

,Student_ID,Subject,Assignment_Name,Due_Date,Status,Grade_Feedback,Guardian_Signature
0,S12002,Science,Record.,2024-09-10,Not Done,C-,Yes
1,S01255,History,Head Baby.,2024-10-16,Not Done,A+,No
2,S04968,Arabic,Keep Audience Medical Free.,2025-02-11,Done,A+,Yes
3,S07925,Geography,Three Half Peace.,2024-10-03,Done,A+,-
4,S09980,Geography,Assume Particularly.,2024-12-01,Done,B-,No
5,S08309,Geography,Four From Kind Dark.,2024-12-19,Done,A,No
6,S11121,Math,Analysis Late Human.,2024-11-10,Not Done,F,Yes
7,S00175,Arabic,Shake By.,2024-09-09,Done,A,No
8,S02439,Geography,Oil Education Large Wonder.,2025-01-01,Done,C,No
9,S08144,Math,Never Bar Time Personal.,2024-10-15,Not Done,A+,No
10,S08545,Math,Deal Music.,2025-07-02,Done,F,No
11,S00424,History,Sister However.,2024-09-28,Done,B,-
12,S00568,Math,Range Huge.,2025-01-28,Done,A,Yes
13,S07048,Arabic,Music Build Check Force.,2025-02-01,Done,A+,-
14,S08771,Science,Strategy.,2025-02-26,Not Done,A+,Yes

In [5]:
# Mengecek Duplikat dan Info
print(f'Total baris duplikat: {df.duplicated().sum()}')
df.drop_duplicates(inplace=True)
print(f'Total baris setelah menghapus duplikat: {df.duplicated().sum()}')

df.info()

df.to_csv('data_clean/clean_homework_data.csv', index=False)

Total baris duplikat: 0
Total baris setelah menghapus duplikat: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60780 entries, 0 to 60779
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          60780 non-null  object
 1   Subject             60780 non-null  object
 2   Assignment_Name     60780 non-null  object
 3   Due_Date            60780 non-null  datetime64[ns]
 4   Status              60780 non-null  object
 5   Grade_Feedback      60780 non-null  object
 6   Guardian_Signature  60780 non-null  object
dtypes: datetime64[ns](1), object(6)
memory usage: 3.2+ MB