In [1]:
import pandas as pd
import numpy as np

In [2]:
# Inisialisasi Data
df = pd.read_csv('data_raw/students.csv', sep=',')
df.columns = df.columns.str.strip()

In [3]:
# Feature Engineering
# Membuat Kolom Baru dengan Nama Emergency_Contact_Ext 
df['Emergency_Contact_Ext'] = df['Emergency_Contact'].str.split('x').str[1].fillna('-')

df.head(15)

,Student_ID,Full_Name,Date_of_Birth,Grade_Level,Emergency_Contact,Emergency_Contact_Ext
0,S00001,Donna Williams,2007-02-10,Grade 3,781-534-4258x9046,9046
1,S00002,John Stafford,2014-11-26,Grade 5,+1-782-691-6291x99704,99704
2,S00003,Chad Harper,2017-02-07,Grade 3,308.517.3750,-
3,S00004,Anthony Martin,11-10-2014,Grade 5,306-771-1524x116,116
4,S00005,Mary Stone,04-01-2016,Grade 3,+1-794-484-8495x7772,7772
5,S00006,Joe Wells,2017-06-29,Grade 2,+1-933-864-5644x501,501
6,S00007,Margaret Nixon,2009-12-04,Grade 4,706.708.0421x412,412
7,S00008,James Wheeler,2011-01-25,Grade 1,(605)818-0057x877,877
8,S00009,Benjamin Cook,2007-10-04,Grade 4,(489)503-7511x611,611
9,S00010,Aaron Callahan,2012-02-18,Grade 4,NaN,-
10,S00011,christopher church,2008-02-23,Grade 1,NaN,-
11,S00012,Jonathan Solis,2016-07-07,Grade 1,+1-534-253-4789x8656,8656
12,S00013,Robert Sanders,2008-04-30,Grade 2,+1-637-642-1016x7779,7779
13,S00014,Melanie Gilmore,2006-08-19,Grade 4,001-569-842-8327x8506,8506
14,S00015,Alexandria Wallace,2006-06-21,Grade 2,+1-283-259-6520x7061,7061

In [4]:
# Data Transformation
# Mengubah Format Nama dengan Kapital setiap Kata
df['Full_Name'] = df['Full_Name'].str.title()

# Mengubah Format Tanggal pada Kolom Date_of_Birth
df['Date_of_Birth'] = pd.to_datetime(df['Date_of_Birth'], format='mixed', dayfirst=True)

# Mengubah Format pada Kolom Emergency_Contact dan Data Cleaning
df['Emergency_Contact'] = df['Emergency_Contact'].str.split('x').str[0]
df['Emergency_Contact'] = df['Emergency_Contact'].str.replace(r'^(\+1|001)', '', regex=True) # Hapus awalan '+1' ATAU '001' jika ada di bagian paling depan string
df['Emergency_Contact'] = df['Emergency_Contact'].str.replace(r'\D', '', regex=True) # Menghapus semua angka yang bukan angka (titik, strip, kurung, spasi)
df['Emergency_Contact'] = '+1' + df['Emergency_Contact'] 
df['Emergency_Contact'] = df['Emergency_Contact'].fillna('-')

df.head(15)

,Student_ID,Full_Name,Date_of_Birth,Grade_Level,Emergency_Contact,Emergency_Contact_Ext
0,S00001,Donna Williams,2007-02-10,Grade 3,+17815344258,9046
1,S00002,John Stafford,2014-11-26,Grade 5,+17826916291,99704
2,S00003,Chad Harper,2017-02-07,Grade 3,+13085173750,-
3,S00004,Anthony Martin,2014-10-11,Grade 5,+13067711524,116
4,S00005,Mary Stone,2016-01-04,Grade 3,+17944848495,7772
5,S00006,Joe Wells,2017-06-29,Grade 2,+19338645644,501
6,S00007,Margaret Nixon,2009-12-04,Grade 4,+17067080421,412
7,S00008,James Wheeler,2011-01-25,Grade 1,+16058180057,877
8,S00009,Benjamin Cook,2007-10-04,Grade 4,+14895037511,611
9,S00010,Aaron Callahan,2012-02-18,Grade 4,-,-
10,S00011,Christopher Church,2008-02-23,Grade 1,-,-
11,S00012,Jonathan Solis,2016-07-07,Grade 1,+15342534789,8656
12,S00013,Robert Sanders,2008-04-30,Grade 2,+16376421016,7779
13,S00014,Melanie Gilmore,2006-08-19,Grade 4,+15698428327,8506
14,S00015,Alexandria Wallace,2006-06-21,Grade 2,+12832596520,7061

In [5]:
# Mengecek Duplikat, Jumlah Data pada Dataset, dan Info
print(f'Total baris duplikat: {df.duplicated().sum()}')
df.drop_duplicates(inplace=True)
print(f'Total baris setelah menghapus duplikat: {df.duplicated().sum()}')

print(f'Total data pada dataset Attendance: {df.shape} [baris, kolom]')

df.info()

df.to_csv('data_clean/clean_students_data.csv', index=False)

Total baris duplikat: 0
Total baris setelah menghapus duplikat: 0
Total data pada dataset Attendance: (12156, 6) [baris, kolom]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12156 entries, 0 to 12155
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             12156 non-null  object
 1   Full_Name              12156 non-null  object
 2   Date_of_Birth          12156 non-null  datetime64[ns]
 3   Grade_Level            12156 non-null  object
 4   Emergency_Contact      12156 non-null  object
 5   Emergency_Contact_Ext  12156 non-null  object
dtypes: datetime64[ns](1), object(5)
memory usage: 569.9+ KB